package com.ytdinfo.keephealth.zhangyuhui.view.ichnography;

import java.util.ArrayList;

import android.graphics.Point;

import com.ytdinfo.keephealth.zhangyuhui.adapte.IAOrganz;
import com.ytdinfo.keephealth.zhangyuhui.adapte.IAOrganzCity;
import com.ytdinfo.keephealth.zhangyuhui.adapte.IAOrganzHttp;
import com.ytdinfo.keephealth.zhangyuhui.common.IALiteral;
import com.ytdinfo.keephealth.zhangyuhui.model.IARoomName;
import com.ytdinfo.keephealth.zhangyuhui.model.IARoomPointModel;

/**
 * @author Administrator 现在已知情况下。房间号码和房间点阵。这是一个配置类。
 */
public class IAPoisDataConfig {
	/**
	 * 获取静态点所在位置和房间号码对应的情况。
	 * 
	 * @param arg
	 * @param roomName
	 * @return
	 */
	public static ArrayList<IARoomPointModel> getData(int[][] arg,
			int[] roomName) {
		ArrayList<IARoomPointModel> data = new ArrayList<IARoomPointModel>();
		int arglen = arg.length;
		for (int i = 0, len = roomName.length; i < len; i++) {
			ArrayList<Point> list = new ArrayList<Point>();
			if (arglen == len) {
				for (int j = 0; j < arg[i].length; j += 2) {
					list.add(new Point(arg[i][j], arg[i][j + 1]));
				}
			}
			data.add(new IARoomPointModel(roomName[i], list, 0, 0, 0));
		}
		return data;
	}

	/**
	 * 获取到绑定机构的房间号码和科室名称。
	 * 
	 * @param room
	 * @param name
	 * @return
	 */
	public static ArrayList<IARoomName> getRoomName(int[] room, String[] name) {
		ArrayList<IARoomName> list = new ArrayList<IARoomName>();
		if (room.length == name.length) {
			for (int i = 0, len = room.length; i < len; i++) {
				list.add(new IARoomName(room[i], name[i], room[i], name[i]));
			}
			return list;
		} else {
			return null;
		}
	}

	/**
	 * 假如次流程是写死状态。则进行获取绑定即可，獲取頂部下拉列表。
	 * 
	 * @return
	 */
	public static IAOrganzHttp getOrg() {
		IAOrganzHttp http = new IAOrganzHttp();
		http.code = 200;
		http.data = new ArrayList<IAOrganzCity>();
		ArrayList<IAOrganz> shanghai = new ArrayList<IAOrganz>();
		int[] st = { 1 };
		shanghai.add(new IAOrganz(31, "八百伴体检机构", st));
		shanghai.add(new IAOrganz(12, "静安体检机构", st));
		shanghai.add(new IAOrganz(24, "徐汇体检机构", st));
		http.data.add(new IAOrganzCity("上海", shanghai));
		return http;
	}

	// 获取平面图资料八百伴对应的平面图资料

	public static int babaibanw = 2000;
	public static int babaibanh = 1124;
	public static int[][] babaiban = {
			{/* 眼科 */IALiteral.width * 208 / babaibanw,
					IALiteral.width * 38 / babaibanw,
					IALiteral.width * 342 / babaibanw,
					IALiteral.width * 38 / babaibanw,
					IALiteral.width * 342 / babaibanw,
					IALiteral.width * 142 / babaibanw,
					IALiteral.width * 208 / babaibanw,
					IALiteral.width * 142 / babaibanw },
			{/* 眼科 */IALiteral.width * 346 / babaibanw,
					IALiteral.width * 38 / babaibanw,
					IALiteral.width * 484 / babaibanw,
					IALiteral.width * 38 / babaibanw,
					IALiteral.width * 484 / babaibanw,
					IALiteral.width * 142 / babaibanw,
					IALiteral.width * 346 / babaibanw,
					IALiteral.width * 142 / babaibanw },
			{/* 视力 */IALiteral.width * 488 / babaibanw,
					IALiteral.width * 38 / babaibanw,
					IALiteral.width * 622 / babaibanw,
					IALiteral.width * 38 / babaibanw,
					IALiteral.width * 622 / babaibanw,
					IALiteral.width * 142 / babaibanw,
					IALiteral.width * 488 / babaibanw,
					IALiteral.width * 142 / babaibanw },
			{ /* 备用 */IALiteral.width * 55 / babaibanw,
					IALiteral.width * 222 / babaibanw,
					IALiteral.width * 206 / babaibanw,
					IALiteral.width * 222 / babaibanw,
					IALiteral.width * 206 / babaibanw,
					IALiteral.width * 324 / babaibanw,
					IALiteral.width * 55 / babaibanw,
					IALiteral.width * 324 / babaibanw },
			{/* 外科 */IALiteral.width * 55 / babaibanw,
					IALiteral.width * 438 / babaibanw,
					IALiteral.width * 206 / babaibanw,
					IALiteral.width * 438 / babaibanw,
					IALiteral.width * 206 / babaibanw,
					IALiteral.width * 526 / babaibanw,
					IALiteral.width * 55 / babaibanw,
					IALiteral.width * 526 / babaibanw },
			{/* 外科 */IALiteral.width * 55 / babaibanw,
					IALiteral.width * 530 / babaibanw,
					IALiteral.width * 206 / babaibanw,
					IALiteral.width * 530 / babaibanw,
					IALiteral.width * 206 / babaibanw,
					IALiteral.width * 616 / babaibanw,
					IALiteral.width * 55 / babaibanw,
					IALiteral.width * 616 / babaibanw },
			{ /* 备用 */IALiteral.width * 55 / babaibanw,
					IALiteral.width * 620 / babaibanw,
					IALiteral.width * 206 / babaibanw,
					IALiteral.width * 620 / babaibanw,
					IALiteral.width * 206 / babaibanw,
					IALiteral.width * 748 / babaibanw,
					IALiteral.width * 55 / babaibanw,
					IALiteral.width * 748 / babaibanw },
			{/* 采血处 */IALiteral.width * 55 / babaibanw,
					IALiteral.width * 752 / babaibanw,
					IALiteral.width * 206 / babaibanw,
					IALiteral.width * 752 / babaibanw,
					IALiteral.width * 206 / babaibanw,
					IALiteral.width * 940 / babaibanw,
					IALiteral.width * 55 / babaibanw,
					IALiteral.width * 940 / babaibanw },
			{/* B超彩超室 */IALiteral.width * 260 / babaibanw,
					IALiteral.width * 224 / babaibanw,
					IALiteral.width * 368 / babaibanw,
					IALiteral.width * 224 / babaibanw,
					IALiteral.width * 368 / babaibanw,
					IALiteral.width * 327 / babaibanw,
					IALiteral.width * 260 / babaibanw,
					IALiteral.width * 327 / babaibanw },
			{/* B超彩超室 */IALiteral.width * 372 / babaibanw,
					IALiteral.width * 224 / babaibanw,
					IALiteral.width * 484 / babaibanw,
					IALiteral.width * 224 / babaibanw,
					IALiteral.width * 484 / babaibanw,
					IALiteral.width * 327 / babaibanw,
					IALiteral.width * 372 / babaibanw,
					IALiteral.width * 327 / babaibanw },
			{/* B超 彩超室 */IALiteral.width * 488 / babaibanw,
					IALiteral.width * 224 / babaibanw,
					IALiteral.width * 620 / babaibanw,
					IALiteral.width * 224 / babaibanw,
					IALiteral.width * 620 / babaibanw,
					IALiteral.width * 327 / babaibanw,
					IALiteral.width * 488 / babaibanw,
					IALiteral.width * 327 / babaibanw },
			{/* 内科 */IALiteral.width * 260 / babaibanw,
					IALiteral.width * 330 / babaibanw,
					IALiteral.width * 368 / babaibanw,
					IALiteral.width * 330 / babaibanw,
					IALiteral.width * 368 / babaibanw,
					IALiteral.width * 436 / babaibanw,
					IALiteral.width * 260 / babaibanw,
					IALiteral.width * 436 / babaibanw },
			{/* 内科 */IALiteral.width * 372 / babaibanw,
					IALiteral.width * 330 / babaibanw,
					IALiteral.width * 484 / babaibanw,
					IALiteral.width * 330 / babaibanw,
					IALiteral.width * 484 / babaibanw,
					IALiteral.width * 436 / babaibanw,
					IALiteral.width * 372 / babaibanw,
					IALiteral.width * 436 / babaibanw },
			{/* 心电图 */IALiteral.width * 488 / babaibanw,
					IALiteral.width * 330 / babaibanw,
					IALiteral.width * 620 / babaibanw,
					IALiteral.width * 330 / babaibanw,
					IALiteral.width * 620 / babaibanw,
					IALiteral.width * 436 / babaibanw,
					IALiteral.width * 488 / babaibanw,
					IALiteral.width * 436 / babaibanw },
			{/* 内科 */IALiteral.width * 426 / babaibanw,
					IALiteral.width * 438 / babaibanw,
					IALiteral.width * 540 / babaibanw,
					IALiteral.width * 438 / babaibanw,
					IALiteral.width * 540 / babaibanw,
					IALiteral.width * 540 / babaibanw,
					IALiteral.width * 426 / babaibanw,
					IALiteral.width * 540 / babaibanw },
			{/* 内科 */IALiteral.width * 428 / babaibanw,
					IALiteral.width * 438 / babaibanw,
					IALiteral.width * 540 / babaibanw,
					IALiteral.width * 438 / babaibanw,
					IALiteral.width * 540 / babaibanw,
					IALiteral.width * 540 / babaibanw,
					IALiteral.width * 428 / babaibanw,
					IALiteral.width * 540 / babaibanw },
			{/* 心电图 */IALiteral.width * 258 / babaibanw,
					IALiteral.width * 544 / babaibanw,
					IALiteral.width * 370 / babaibanw,
					IALiteral.width * 544 / babaibanw,
					IALiteral.width * 370 / babaibanw,
					IALiteral.width * 648 / babaibanw,
					IALiteral.width * 258 / babaibanw,
					IALiteral.width * 648 / babaibanw },
			{/* 心电图 */IALiteral.width * 374 / babaibanw,
					IALiteral.width * 544 / babaibanw,
					IALiteral.width * 540 / babaibanw,
					IALiteral.width * 544 / babaibanw,
					IALiteral.width * 540 / babaibanw,
					IALiteral.width * 648 / babaibanw,
					IALiteral.width * 374 / babaibanw,
					IALiteral.width * 648 / babaibanw },
			{/* 心电图110 */IALiteral.width * 374 / babaibanw,
					IALiteral.width * 544 / babaibanw,
					IALiteral.width * 540 / babaibanw,
					IALiteral.width * 544 / babaibanw,
					IALiteral.width * 540 / babaibanw,
					IALiteral.width * 648 / babaibanw,
					IALiteral.width * 374 / babaibanw,
					IALiteral.width * 648 / babaibanw },
			{/* 耳鼻喉 */IALiteral.width * 258 / babaibanw,
					IALiteral.width * 652 / babaibanw,
					IALiteral.width * 330 / babaibanw,
					IALiteral.width * 652 / babaibanw,
					IALiteral.width * 330 / babaibanw,
					IALiteral.width * 810 / babaibanw,
					IALiteral.width * 258 / babaibanw,
					IALiteral.width * 810 / babaibanw },
			{/* 耳鼻喉 */IALiteral.width * 334 / babaibanw,
					IALiteral.width * 652 / babaibanw,
					IALiteral.width * 406 / babaibanw,
					IALiteral.width * 652 / babaibanw,
					IALiteral.width * 406 / babaibanw,
					IALiteral.width * 810 / babaibanw,
					IALiteral.width * 334 / babaibanw,
					IALiteral.width * 810 / babaibanw },
			{/* 一般检查 */IALiteral.width * 410 / babaibanw,
					IALiteral.width * 652 / babaibanw,
					IALiteral.width * 498 / babaibanw,
					IALiteral.width * 652 / babaibanw,
					IALiteral.width * 498 / babaibanw,
					IALiteral.width * 810 / babaibanw,
					IALiteral.width * 410 / babaibanw,
					IALiteral.width * 810 / babaibanw },
			{/* 外科 */IALiteral.width * 502 / babaibanw,
					IALiteral.width * 652 / babaibanw,
					IALiteral.width * 590 / babaibanw,
					IALiteral.width * 652 / babaibanw,
					IALiteral.width * 590 / babaibanw,
					IALiteral.width * 810 / babaibanw,
					IALiteral.width * 502 / babaibanw,
					IALiteral.width * 810 / babaibanw },
			{/* B超彩超室 */IALiteral.width * 674 / babaibanw,
					IALiteral.width * 188 / babaibanw,
					IALiteral.width * 820 / babaibanw,
					IALiteral.width * 188 / babaibanw,
					IALiteral.width * 820 / babaibanw,
					IALiteral.width * 313 / babaibanw,
					IALiteral.width * 674 / babaibanw,
					IALiteral.width * 313 / babaibanw },
			{/* 妇科 */IALiteral.width * 674 / babaibanw,
					IALiteral.width * 388 / babaibanw,
					IALiteral.width * 820 / babaibanw,
					IALiteral.width * 388 / babaibanw,
					IALiteral.width * 820 / babaibanw,
					IALiteral.width * 517 / babaibanw,
					IALiteral.width * 674 / babaibanw,
					IALiteral.width * 517 / babaibanw },
			{/* 妇科 */IALiteral.width * 674 / babaibanw,
					IALiteral.width * 520 / babaibanw,
					IALiteral.width * 820 / babaibanw,
					IALiteral.width * 520 / babaibanw,
					IALiteral.width * 820 / babaibanw,
					IALiteral.width * 648 / babaibanw,
					IALiteral.width * 674 / babaibanw,
					IALiteral.width * 648 / babaibanw },
			{/* 内科 */IALiteral.width * 674 / babaibanw,
					IALiteral.width * 654 / babaibanw,
					IALiteral.width * 820 / babaibanw,
					IALiteral.width * 654 / babaibanw,
					IALiteral.width * 820 / babaibanw,
					IALiteral.width * 780 / babaibanw,
					IALiteral.width * 674 / babaibanw,
					IALiteral.width * 780 / babaibanw },
			{/* 口腔科 */IALiteral.width * 1204 / babaibanw,
					IALiteral.width * 182 / babaibanw,
					IALiteral.width * 1395 / babaibanw,
					IALiteral.width * 182 / babaibanw,
					IALiteral.width * 1298 / babaibanw,
					IALiteral.width * 277 / babaibanw },
			{/* 中医科 */IALiteral.width * 1300 / babaibanw,
					IALiteral.width * 280 / babaibanw,
					IALiteral.width * 1420 / babaibanw,
					IALiteral.width * 162 / babaibanw,
					IALiteral.width * 1478 / babaibanw,
					IALiteral.width * 220 / babaibanw,
					IALiteral.width * 1356 / babaibanw,
					IALiteral.width * 338 / babaibanw },
			{/* 钼靶室 */IALiteral.width * 1361 / babaibanw,
					IALiteral.width * 340 / babaibanw,
					IALiteral.width * 1481 / babaibanw,
					IALiteral.width * 224 / babaibanw,
					IALiteral.width * 1541 / babaibanw,
					IALiteral.width * 282 / babaibanw,
					IALiteral.width * 1420 / babaibanw,
					IALiteral.width * 400 / babaibanw },
			{/* DR */IALiteral.width * 1528 / babaibanw,
					IALiteral.width * 424 / babaibanw,
					IALiteral.width * 1609 / babaibanw,
					IALiteral.width * 345 / babaibanw,
					IALiteral.width * 1645 / babaibanw,
					IALiteral.width * 345 / babaibanw,
					IALiteral.width * 1645 / babaibanw,
					IALiteral.width * 462 / babaibanw,
					IALiteral.width * 1537 / babaibanw,
					IALiteral.width * 462 / babaibanw,
					IALiteral.width * 1537 / babaibanw,
					IALiteral.width * 424 / babaibanw },
			{/* CT室 */IALiteral.width * 1648 / babaibanw,
					IALiteral.width * 345 / babaibanw,
					IALiteral.width * 1808 / babaibanw,
					IALiteral.width * 345 / babaibanw,
					IALiteral.width * 1808 / babaibanw,
					IALiteral.width * 462 / babaibanw,
					IALiteral.width * 1648 / babaibanw,
					IALiteral.width * 462 / babaibanw },
			{/* 动脉硬化 */IALiteral.width * 1717 / babaibanw,
					IALiteral.width * 552 / babaibanw,
					IALiteral.width * 1808 / babaibanw,
					IALiteral.width * 467 / babaibanw,
					IALiteral.width * 1808 / babaibanw,
					IALiteral.width * 474 / babaibanw,
					IALiteral.width * 1866 / babaibanw,
					IALiteral.width * 529 / babaibanw,
					IALiteral.width * 1777 / babaibanw,
					IALiteral.width * 613 / babaibanw },
			{/* 备用 */IALiteral.width * 1811 / babaibanw,
					IALiteral.width * 639 / babaibanw,
					IALiteral.width * 1893 / babaibanw,
					IALiteral.width * 556 / babaibanw,
					IALiteral.width * 1950 / babaibanw,
					IALiteral.width * 611 / babaibanw,
					IALiteral.width * 1867 / babaibanw,
					IALiteral.width * 694 / babaibanw },
			{/* 骨密度 */IALiteral.width * 1678 / babaibanw,
					IALiteral.width * 772 / babaibanw,
					IALiteral.width * 1808 / babaibanw,
					IALiteral.width * 642 / babaibanw,
					IALiteral.width * 1864 / babaibanw,
					IALiteral.width * 698 / babaibanw,
					IALiteral.width * 1735 / babaibanw,
					IALiteral.width * 829 / babaibanw },
			{/* 经颅多普勒 */IALiteral.width * 1542 / babaibanw,
					IALiteral.width * 907 / babaibanw,
					IALiteral.width * 1675 / babaibanw,
					IALiteral.width * 775 / babaibanw,
					IALiteral.width * 1731 / babaibanw,
					IALiteral.width * 832 / babaibanw,
					IALiteral.width * 1600 / babaibanw,
					IALiteral.width * 965 / babaibanw },
			{/* 肺功能 */IALiteral.width * 1425 / babaibanw,
					IALiteral.width * 940 / babaibanw,
					IALiteral.width * 1570 / babaibanw,
					IALiteral.width * 940 / babaibanw,
					IALiteral.width * 1600 / babaibanw,
					IALiteral.width * 970 / babaibanw,
					IALiteral.width * 1600 / babaibanw,
					IALiteral.width * 1042 / babaibanw,
					IALiteral.width * 1425 / babaibanw,
					IALiteral.width * 1042 / babaibanw },
			{/* 000 */IALiteral.width * 823 / babaibanw,
					IALiteral.width * 196 / babaibanw,
					IALiteral.width * 942 / babaibanw,
					IALiteral.width * 311 / babaibanw,
					IALiteral.width * 878 / babaibanw,
					IALiteral.width * 376 / babaibanw,
					IALiteral.width * 823 / babaibanw,
					IALiteral.width * 321 / babaibanw } };

	// 获取平面图资料静安对应的平面图资料

	public static int jinganw = 2000;
	public static int jinganh = 1124;
	public static int[][] jingan = {
			{/* 检验科 */IALiteral.width * 518 / jinganw,
					IALiteral.width * 151 / jinganw,
					IALiteral.width * 780 / jinganw,
					IALiteral.width * 9 / jinganw,
					IALiteral.width * 802 / jinganw,
					IALiteral.width * 9 / jinganw,
					IALiteral.width * 802 / jinganw,
					IALiteral.width * 110 / jinganw,
					IALiteral.width * 518 / jinganw,
					IALiteral.width * 269 / jinganw },
			{/* DR房間 */IALiteral.width * 806 / jinganw,
					IALiteral.width * 9 / jinganw,
					IALiteral.width * 1079 / jinganw,
					IALiteral.width * 9 / jinganw,
					IALiteral.width * 1079 / jinganw,
					IALiteral.width * 112 / jinganw,
					IALiteral.width * 806 / jinganw,
					IALiteral.width * 112 / jinganw },
			{/* 钼钯 */IALiteral.width * 1082 / jinganw,
					IALiteral.width * 9 / jinganw,
					IALiteral.width * 1247 / jinganw,
					IALiteral.width * 9 / jinganw,
					IALiteral.width * 1247 / jinganw,
					IALiteral.width * 112 / jinganw,
					IALiteral.width * 1082 / jinganw,
					IALiteral.width * 112 / jinganw },
			// 进行修改
			{/* 备用227 */IALiteral.width * 1236 / jinganw,
					IALiteral.width * 170 / jinganw,
					IALiteral.width * 1329 / jinganw,
					IALiteral.width * 87 / jinganw,
					IALiteral.width * 1351 / jinganw,
					IALiteral.width * 110 / jinganw,
					IALiteral.width * 1260 / jinganw,
					IALiteral.width * 194 / jinganw },
			{/* 肺功能228 */IALiteral.width * 1259 / jinganw,
					IALiteral.width * 198 / jinganw,
					IALiteral.width * 1354 / jinganw,
					IALiteral.width * 115 / jinganw,
					IALiteral.width * 1408 / jinganw,
					IALiteral.width * 166 / jinganw,
					IALiteral.width * 1317 / jinganw,
					IALiteral.width * 251 / jinganw },
			{/* 骨密度 */IALiteral.width * 1065 / jinganw,
					IALiteral.width * 144 / jinganw,
					IALiteral.width * 1148 / jinganw,
					IALiteral.width * 228 / jinganw,
					IALiteral.width * 1092 / jinganw,
					IALiteral.width * 285 / jinganw,
					IALiteral.width * 1008 / jinganw,
					IALiteral.width * 201 / jinganw },
			{/* 经颅多普勒 */IALiteral.width * 1003 / jinganw,
					IALiteral.width * 204 / jinganw,
					IALiteral.width * 1124 / jinganw,
					IALiteral.width * 324 / jinganw,
					IALiteral.width * 1069 / jinganw,
					IALiteral.width * 378 / jinganw,
					IALiteral.width * 948 / jinganw,
					IALiteral.width * 260 / jinganw },
			{/* B超219 */IALiteral.width * 452 / jinganw,
					IALiteral.width * 313 / jinganw,
					IALiteral.width * 583 / jinganw,
					IALiteral.width * 313 / jinganw,
					IALiteral.width * 583 / jinganw,
					IALiteral.width * 392 / jinganw,
					IALiteral.width * 452 / jinganw,
					IALiteral.width * 392 / jinganw },
			{/* B超218 */IALiteral.width * 218 / jinganw,
					IALiteral.width * 313 / jinganw,
					IALiteral.width * 446 / jinganw,
					IALiteral.width * 313 / jinganw,
					IALiteral.width * 446 / jinganw,
					IALiteral.width * 392 / jinganw,
					IALiteral.width * 218 / jinganw,
					IALiteral.width * 392 / jinganw },
			{/* 心电图217 */IALiteral.width * 218 / jinganw,
					IALiteral.width * 395 / jinganw,
					IALiteral.width * 422 / jinganw,
					IALiteral.width * 395 / jinganw,
					IALiteral.width * 422 / jinganw,
					IALiteral.width * 465 / jinganw,
					IALiteral.width * 218 / jinganw,
					IALiteral.width * 465 / jinganw },
			{/* 内科238 */IALiteral.width * 1128 / jinganw,
					IALiteral.width * 331 / jinganw,
					IALiteral.width * 1201 / jinganw,
					IALiteral.width * 402 / jinganw,
					IALiteral.width * 1146 / jinganw,
					IALiteral.width * 456 / jinganw,
					IALiteral.width * 1072 / jinganw,
					IALiteral.width * 384 / jinganw },
			{/* 239 */IALiteral.width * 1186 / jinganw,
					IALiteral.width * 268 / jinganw,
					IALiteral.width * 1260 / jinganw,
					IALiteral.width * 340 / jinganw,
					IALiteral.width * 1203 / jinganw,
					IALiteral.width * 398 / jinganw,
					IALiteral.width * 1130 / jinganw,
					IALiteral.width * 325 / jinganw },
			{/* 226 */IALiteral.width * 1318 / jinganw,
					IALiteral.width * 258 / jinganw,
					IALiteral.width * 1413 / jinganw,
					IALiteral.width * 174 / jinganw,
					IALiteral.width * 1470 / jinganw,
					IALiteral.width * 226 / jinganw,
					IALiteral.width * 1374 / jinganw,
					IALiteral.width * 311 / jinganw },
			{/* 报告室 */IALiteral.width * 1473 / jinganw,
					IALiteral.width * 230 / jinganw,
					IALiteral.width * 1617 / jinganw,
					IALiteral.width * 374 / jinganw,
					IALiteral.width * 1314 / jinganw,
					IALiteral.width * 374 / jinganw },
			{/* B超253 */IALiteral.width * 1623 / jinganw,
					IALiteral.width * 377 / jinganw,
					IALiteral.width * 1725 / jinganw,
					IALiteral.width * 377 / jinganw,
					IALiteral.width * 1725 / jinganw,
					IALiteral.width * 508 / jinganw,
					IALiteral.width * 1623 / jinganw,
					IALiteral.width * 508 / jinganw },
			{/* 男外科 252 */IALiteral.width * 1527 / jinganw,
					IALiteral.width * 377 / jinganw,
					IALiteral.width * 1619 / jinganw,
					IALiteral.width * 377 / jinganw,
					IALiteral.width * 1619 / jinganw,
					IALiteral.width * 508 / jinganw,
					IALiteral.width * 1527 / jinganw,
					IALiteral.width * 508 / jinganw },
			{/* 男外科 251 */IALiteral.width * 1425 / jinganw,
					IALiteral.width * 377 / jinganw,
					IALiteral.width * 1523 / jinganw,
					IALiteral.width * 377 / jinganw,
					IALiteral.width * 1523 / jinganw,
					IALiteral.width * 508 / jinganw,
					IALiteral.width * 1425 / jinganw,
					IALiteral.width * 508 / jinganw },
			{/* 心电图 250 */IALiteral.width * 1305 / jinganw,
					IALiteral.width * 377 / jinganw,
					IALiteral.width * 1415 / jinganw,
					IALiteral.width * 377 / jinganw,
					IALiteral.width * 1415 / jinganw,
					IALiteral.width * 508 / jinganw,
					IALiteral.width * 1305 / jinganw,
					IALiteral.width * 508 / jinganw },
			{/* 心电图 216 */IALiteral.width * 221 / jinganw,
					IALiteral.width * 469 / jinganw,
					IALiteral.width * 424 / jinganw,
					IALiteral.width * 469 / jinganw,
					IALiteral.width * 424 / jinganw,
					IALiteral.width * 539 / jinganw,
					IALiteral.width * 221 / jinganw,
					IALiteral.width * 539 / jinganw },
			{/* 妇科212 */IALiteral.width * 220 / jinganw,
					IALiteral.width * 544 / jinganw,
					IALiteral.width * 348 / jinganw,
					IALiteral.width * 544 / jinganw,
					IALiteral.width * 348 / jinganw,
					IALiteral.width * 711 / jinganw,
					IALiteral.width * 220 / jinganw,
					IALiteral.width * 711 / jinganw },
			{/* 妇科213 */IALiteral.width * 352 / jinganw,
					IALiteral.width * 543 / jinganw,
					IALiteral.width * 470 / jinganw,
					IALiteral.width * 543 / jinganw,
					IALiteral.width * 470 / jinganw,
					IALiteral.width * 623 / jinganw,
					IALiteral.width * 352 / jinganw,
					IALiteral.width * 623 / jinganw },
			{/* 外科215 */IALiteral.width * 475 / jinganw,
					IALiteral.width * 543 / jinganw,
					IALiteral.width * 585 / jinganw,
					IALiteral.width * 543 / jinganw,
					IALiteral.width * 585 / jinganw,
					IALiteral.width * 623 / jinganw,
					IALiteral.width * 475 / jinganw,
					IALiteral.width * 623 / jinganw },
			{/* B超255 */IALiteral.width * 1649 / jinganw,
					IALiteral.width * 513 / jinganw,
					IALiteral.width * 1726 / jinganw,
					IALiteral.width * 513 / jinganw,
					IALiteral.width * 1726 / jinganw,
					IALiteral.width * 593 / jinganw,
					IALiteral.width * 1649 / jinganw,
					IALiteral.width * 593 / jinganw },
			{/* 备用237 */IALiteral.width * 1293 / jinganw,
					IALiteral.width * 625 / jinganw,
					IALiteral.width * 1368 / jinganw,
					IALiteral.width * 559 / jinganw,
					IALiteral.width * 1408 / jinganw,
					IALiteral.width * 596 / jinganw,
					IALiteral.width * 1334 / jinganw,
					IALiteral.width * 666 / jinganw },
			{/* 备用236 */IALiteral.width * 1147 / jinganw,
					IALiteral.width * 769 / jinganw,
					IALiteral.width * 1220 / jinganw,
					IALiteral.width * 696 / jinganw,
					IALiteral.width * 1261 / jinganw,
					IALiteral.width * 737 / jinganw,
					IALiteral.width * 1184 / jinganw,
					IALiteral.width * 814 / jinganw },
			{/* 眼科208 */IALiteral.width * 665 / jinganw,
					IALiteral.width * 615 / jinganw,
					IALiteral.width * 802 / jinganw,
					IALiteral.width * 615 / jinganw,
					IALiteral.width * 802 / jinganw,
					IALiteral.width * 699 / jinganw,
					IALiteral.width * 665 / jinganw,
					IALiteral.width * 699 / jinganw },
			{/* B超211 */IALiteral.width * 220 / jinganw,
					IALiteral.width * 716 / jinganw,
					IALiteral.width * 373 / jinganw,
					IALiteral.width * 716 / jinganw,
					IALiteral.width * 373 / jinganw,
					IALiteral.width * 796 / jinganw,
					IALiteral.width * 220 / jinganw,
					IALiteral.width * 796 / jinganw },
			{/* B超210 */IALiteral.width * 379 / jinganw,
					IALiteral.width * 716 / jinganw,
					IALiteral.width * 479 / jinganw,
					IALiteral.width * 716 / jinganw,
					IALiteral.width * 479 / jinganw,
					IALiteral.width * 796 / jinganw,
					IALiteral.width * 379 / jinganw,
					IALiteral.width * 796 / jinganw },
			{/* 内科209 */IALiteral.width * 482 / jinganw,
					IALiteral.width * 716 / jinganw,
					IALiteral.width * 584 / jinganw,
					IALiteral.width * 716 / jinganw,
					IALiteral.width * 584 / jinganw,
					IALiteral.width * 796 / jinganw,
					IALiteral.width * 482 / jinganw,
					IALiteral.width * 796 / jinganw },
			{/* 视力207 */IALiteral.width * 665 / jinganw,
					IALiteral.width * 704 / jinganw,
					IALiteral.width * 802 / jinganw,
					IALiteral.width * 704 / jinganw,
					IALiteral.width * 802 / jinganw,
					IALiteral.width * 791 / jinganw,
					IALiteral.width * 665 / jinganw,
					IALiteral.width * 791 / jinganw },
			{/* 233 */IALiteral.width * 806 / jinganw,
					IALiteral.width * 612 / jinganw,
					IALiteral.width * 839 / jinganw,
					IALiteral.width * 612 / jinganw,
					IALiteral.width * 946 / jinganw,
					IALiteral.width * 719 / jinganw,
					IALiteral.width * 946 / jinganw,
					IALiteral.width * 804 / jinganw,
					IALiteral.width * 806 / jinganw,
					IALiteral.width * 804 / jinganw },
			{/* 备用235 */IALiteral.width * 898 / jinganw,
					IALiteral.width * 549 / jinganw,
					IALiteral.width * 1011 / jinganw,
					IALiteral.width * 663 / jinganw,
					IALiteral.width * 954 / jinganw,
					IALiteral.width * 720 / jinganw,
					IALiteral.width * 840 / jinganw,
					IALiteral.width * 608 / jinganw },
			{/* 231 */IALiteral.width * 1038 / jinganw,
					IALiteral.width * 818 / jinganw,
					IALiteral.width * 1177 / jinganw,
					IALiteral.width * 818 / jinganw,
					IALiteral.width * 1177 / jinganw,
					IALiteral.width * 876 / jinganw,
					IALiteral.width * 1038 / jinganw,
					IALiteral.width * 876 / jinganw },
			{/* 232 */IALiteral.width * 806 / jinganw,
					IALiteral.width * 808 / jinganw,
					IALiteral.width * 946 / jinganw,
					IALiteral.width * 808 / jinganw,
					IALiteral.width * 946 / jinganw,
					IALiteral.width * 885 / jinganw,
					IALiteral.width * 806 / jinganw,
					IALiteral.width * 885 / jinganw },
			{/* 耳鼻喉科206 */IALiteral.width * 663 / jinganw,
					IALiteral.width * 796 / jinganw,
					IALiteral.width * 802 / jinganw,
					IALiteral.width * 796 / jinganw,
					IALiteral.width * 802 / jinganw,
					IALiteral.width * 905 / jinganw,
					IALiteral.width * 663 / jinganw,
					IALiteral.width * 905 / jinganw },
			{/* 备用205 */IALiteral.width * 662 / jinganw,
					IALiteral.width * 908 / jinganw,
					IALiteral.width * 802 / jinganw,
					IALiteral.width * 908 / jinganw,
					IALiteral.width * 802 / jinganw,
					IALiteral.width * 961 / jinganw,
					IALiteral.width * 662 / jinganw,
					IALiteral.width * 961 / jinganw },
			{/* 备用203 */IALiteral.width * 662 / jinganw,
					IALiteral.width * 965 / jinganw,
					IALiteral.width * 802 / jinganw,
					IALiteral.width * 965 / jinganw,
					IALiteral.width * 802 / jinganw,
					IALiteral.width * 1022 / jinganw,
					IALiteral.width * 662 / jinganw,
					IALiteral.width * 1022 / jinganw },
			{/* 一般检查228 */IALiteral.width * 806 / jinganw,
					IALiteral.width * 889 / jinganw,
					IALiteral.width * 946 / jinganw,
					IALiteral.width * 889 / jinganw,
					IALiteral.width * 946 / jinganw,
					IALiteral.width * 1021 / jinganw,
					IALiteral.width * 806 / jinganw,
					IALiteral.width * 1021 / jinganw },
			{/* 230 */IALiteral.width * 1037 / jinganw,
					IALiteral.width * 880 / jinganw,
					IALiteral.width * 1177 / jinganw,
					IALiteral.width * 880 / jinganw,
					IALiteral.width * 1177 / jinganw,
					IALiteral.width * 931 / jinganw,
					IALiteral.width * 1037 / jinganw,
					IALiteral.width * 931 / jinganw },
			{/* 229 */IALiteral.width * 1037 / jinganw,
					IALiteral.width * 936 / jinganw,
					IALiteral.width * 1177 / jinganw,
					IALiteral.width * 936 / jinganw,
					IALiteral.width * 1177 / jinganw,
					IALiteral.width * 1032 / jinganw,
					IALiteral.width * 1037 / jinganw,
					IALiteral.width * 1032 / jinganw },
			{/* 采血处201 */IALiteral.width * 501 / jinganw,
					IALiteral.width * 984 / jinganw,
					IALiteral.width * 501 / jinganw,
					IALiteral.width * 1111 / jinganw,
					IALiteral.width * 627 / jinganw,
					IALiteral.width * 1111 / jinganw } };

	// 获取平面图资料TC2对应的平面图资料()徐汇地区的平面图
	public static int xuhuiw = 2000;
	public static int xuhuih = 1124;
	public static int[][] xuhui = {
			{/* DR房間136 */IALiteral.width * 231 / jinganw,
					IALiteral.width * 24 / jinganw,
					IALiteral.width * 428 / jinganw,
					IALiteral.width * 24 / jinganw,
					IALiteral.width * 428 / jinganw,
					IALiteral.width * 172 / jinganw,
					IALiteral.width * 231 / jinganw,
					IALiteral.width * 172 / jinganw },
			{/* CT房間 137 */IALiteral.width * 431 / jinganw,
					IALiteral.width * 24 / jinganw,
					IALiteral.width * 766 / jinganw,
					IALiteral.width * 24 / jinganw,
					IALiteral.width * 766 / jinganw,
					IALiteral.width * 172 / jinganw,
					IALiteral.width * 431 / jinganw,
					IALiteral.width * 172 / jinganw },
			{/* 采血处104 */IALiteral.width * 1590 / jinganw,
					IALiteral.width * 595 / jinganw,
					IALiteral.width * 1732 / jinganw,
					IALiteral.width * 595 / jinganw,
					IALiteral.width * 1732 / jinganw,
					IALiteral.width * 767 / jinganw,
					IALiteral.width * 1590 / jinganw,
					IALiteral.width * 767 / jinganw },
			{/* 检验科105 */IALiteral.width * 1590 / jinganw,
					IALiteral.width * 770 / jinganw,
					IALiteral.width * 1732 / jinganw,
					IALiteral.width * 770 / jinganw,
					IALiteral.width * 1732 / jinganw,
					IALiteral.width * 945 / jinganw,
					IALiteral.width * 1590 / jinganw,
					IALiteral.width * 945 / jinganw },
			{/* 一般项目106 */IALiteral.width * 1536 / jinganw,
					IALiteral.width * 991 / jinganw,
					IALiteral.width * 1732 / jinganw,
					IALiteral.width * 991 / jinganw,
					IALiteral.width * 1732 / jinganw,
					IALiteral.width * 1102 / jinganw,
					IALiteral.width * 1536 / jinganw,
					IALiteral.width * 1102 / jinganw },
			{/* 口腔科107 */IALiteral.width * 1416 / jinganw,
					IALiteral.width * 991 / jinganw,
					IALiteral.width * 1533 / jinganw,
					IALiteral.width * 991 / jinganw,
					IALiteral.width * 1533 / jinganw,
					IALiteral.width * 1102 / jinganw,
					IALiteral.width * 1416 / jinganw,
					IALiteral.width * 1102 / jinganw },
			{/* 心电图108 */IALiteral.width * 1294 / jinganw,
					IALiteral.width * 991 / jinganw,
					IALiteral.width * 1412 / jinganw,
					IALiteral.width * 991 / jinganw,
					IALiteral.width * 1412 / jinganw,
					IALiteral.width * 1102 / jinganw,
					IALiteral.width * 1294 / jinganw,
					IALiteral.width * 1102 / jinganw },
			{/* 心电图109 */IALiteral.width * 1164 / jinganw,
					IALiteral.width * 991 / jinganw,
					IALiteral.width * 1291 / jinganw,
					IALiteral.width * 991 / jinganw,
					IALiteral.width * 1291 / jinganw,
					IALiteral.width * 1102 / jinganw,
					IALiteral.width * 1164 / jinganw,
					IALiteral.width * 1102 / jinganw },
			{/* B超110 */IALiteral.width * 1062 / jinganw,
					IALiteral.width * 991 / jinganw,
					IALiteral.width * 1160 / jinganw,
					IALiteral.width * 991 / jinganw,
					IALiteral.width * 1160 / jinganw,
					IALiteral.width * 1102 / jinganw,
					IALiteral.width * 1062 / jinganw,
					IALiteral.width * 1102 / jinganw },
			{/* B超111 */IALiteral.width * 962 / jinganw,
					IALiteral.width * 991 / jinganw,
					IALiteral.width * 1059 / jinganw,
					IALiteral.width * 991 / jinganw,
					IALiteral.width * 1059 / jinganw,
					IALiteral.width * 1102 / jinganw,
					IALiteral.width * 962 / jinganw,
					IALiteral.width * 1102 / jinganw },
			{/* B超112 */IALiteral.width * 833 / jinganw,
					IALiteral.width * 991 / jinganw,
					IALiteral.width * 958 / jinganw,
					IALiteral.width * 991 / jinganw,
					IALiteral.width * 958 / jinganw,
					IALiteral.width * 1102 / jinganw,
					IALiteral.width * 833 / jinganw,
					IALiteral.width * 1102 / jinganw },
			{/* 钼靶124 */IALiteral.width * 563 / jinganw,
					IALiteral.width * 991 / jinganw,
					IALiteral.width * 829 / jinganw,
					IALiteral.width * 991 / jinganw,
					IALiteral.width * 829 / jinganw,
					IALiteral.width * 1102 / jinganw,
					IALiteral.width * 563 / jinganw,
					IALiteral.width * 1102 / jinganw },
			{/* 多普勒129 */IALiteral.width * 338 / jinganw,
					IALiteral.width * 572 / jinganw,
					IALiteral.width * 562 / jinganw,
					IALiteral.width * 572 / jinganw,
					IALiteral.width * 562 / jinganw,
					IALiteral.width * 711 / jinganw,
					IALiteral.width * 338 / jinganw,
					IALiteral.width * 711 / jinganw },
			{/* 呼气试验肺功能130 */IALiteral.width * 228 / jinganw,
					IALiteral.width * 572 / jinganw,
					IALiteral.width * 335 / jinganw,
					IALiteral.width * 572 / jinganw,
					IALiteral.width * 335 / jinganw,
					IALiteral.width * 711 / jinganw,
					IALiteral.width * 228 / jinganw,
					IALiteral.width * 711 / jinganw },
			{/* 中医科131 */IALiteral.width * 228 / jinganw,
					IALiteral.width * 440 / jinganw,
					IALiteral.width * 340 / jinganw,
					IALiteral.width * 440 / jinganw,
					IALiteral.width * 340 / jinganw,
					IALiteral.width * 536 / jinganw,
					IALiteral.width * 228 / jinganw,
					IALiteral.width * 536 / jinganw },
			{/* 备用室132 */IALiteral.width * 228 / jinganw,
					IALiteral.width * 256 / jinganw,
					IALiteral.width * 340 / jinganw,
					IALiteral.width * 256 / jinganw,
					IALiteral.width * 340 / jinganw,
					IALiteral.width * 408 / jinganw,
					IALiteral.width * 228 / jinganw,
					IALiteral.width * 408 / jinganw },
			{/* 动脉粥样硬化133 */IALiteral.width * 342 / jinganw,
					IALiteral.width * 256 / jinganw,
					IALiteral.width * 452 / jinganw,
					IALiteral.width * 256 / jinganw,
					IALiteral.width * 452 / jinganw,
					IALiteral.width * 408 / jinganw,
					IALiteral.width * 342 / jinganw,
					IALiteral.width * 408 / jinganw },
			{/* 人体成分骨密度134 */IALiteral.width * 455 / jinganw,
					IALiteral.width * 256 / jinganw,
					IALiteral.width * 566 / jinganw,
					IALiteral.width * 256 / jinganw,
					IALiteral.width * 566 / jinganw,
					IALiteral.width * 408 / jinganw,
					IALiteral.width * 455 / jinganw,
					IALiteral.width * 408 / jinganw },
			{/* 视力116 */IALiteral.width * 1279 / jinganw,
					IALiteral.width * 598 / jinganw,
					IALiteral.width * 1435 / jinganw,
					IALiteral.width * 598 / jinganw,
					IALiteral.width * 1435 / jinganw,
					IALiteral.width * 678 / jinganw,
					IALiteral.width * 1279 / jinganw,
					IALiteral.width * 678 / jinganw },
			{/* 眼科115 */IALiteral.width * 1279 / jinganw,
					IALiteral.width * 682 / jinganw,
					IALiteral.width * 1435 / jinganw,
					IALiteral.width * 682 / jinganw,
					IALiteral.width * 1435 / jinganw,
					IALiteral.width * 761 / jinganw,
					IALiteral.width * 1279 / jinganw,
					IALiteral.width * 761 / jinganw },
			{/* 眼科114 */IALiteral.width * 1279 / jinganw,
					IALiteral.width * 765 / jinganw,
					IALiteral.width * 1435 / jinganw,
					IALiteral.width * 765 / jinganw,
					IALiteral.width * 1435 / jinganw,
					IALiteral.width * 840 / jinganw,
					IALiteral.width * 1279 / jinganw,
					IALiteral.width * 840 / jinganw },
			{/* 耳鼻喉113 */IALiteral.width * 1279 / jinganw,
					IALiteral.width * 844 / jinganw,
					IALiteral.width * 1435 / jinganw,
					IALiteral.width * 844 / jinganw,
					IALiteral.width * 1435 / jinganw,
					IALiteral.width * 924 / jinganw,
					IALiteral.width * 1279 / jinganw,
					IALiteral.width * 924 / jinganw },
			{/* 男外科120 */IALiteral.width * 1118 / jinganw,
					IALiteral.width * 598 / jinganw,
					IALiteral.width * 1274 / jinganw,
					IALiteral.width * 598 / jinganw,
					IALiteral.width * 1274 / jinganw,
					IALiteral.width * 678 / jinganw,
					IALiteral.width * 1118 / jinganw,
					IALiteral.width * 678 / jinganw },
			{/* 中医科119 */IALiteral.width * 1118 / jinganw,
					IALiteral.width * 682 / jinganw,
					IALiteral.width * 1274 / jinganw,
					IALiteral.width * 682 / jinganw,
					IALiteral.width * 1274 / jinganw,
					IALiteral.width * 761 / jinganw,
					IALiteral.width * 1118 / jinganw,
					IALiteral.width * 761 / jinganw },
			{/* 男内科118 */IALiteral.width * 1118 / jinganw,
					IALiteral.width * 765 / jinganw,
					IALiteral.width * 1274 / jinganw,
					IALiteral.width * 765 / jinganw,
					IALiteral.width * 1274 / jinganw,
					IALiteral.width * 840 / jinganw,
					IALiteral.width * 1118 / jinganw,
					IALiteral.width * 840 / jinganw },
			{/* 男外科117 */IALiteral.width * 1118 / jinganw,
					IALiteral.width * 844 / jinganw,
					IALiteral.width * 1274 / jinganw,
					IALiteral.width * 844 / jinganw,
					IALiteral.width * 1274 / jinganw,
					IALiteral.width * 924 / jinganw,
					IALiteral.width * 1118 / jinganw,
					IALiteral.width * 924 / jinganw },
			{/* 女心电图123 */IALiteral.width * 891 / jinganw,
					IALiteral.width * 598 / jinganw,
					IALiteral.width * 1024 / jinganw,
					IALiteral.width * 598 / jinganw,
					IALiteral.width * 1024 / jinganw,
					IALiteral.width * 697 / jinganw,
					IALiteral.width * 891 / jinganw,
					IALiteral.width * 697 / jinganw },
			{/* B超122 */IALiteral.width * 891 / jinganw,
					IALiteral.width * 702 / jinganw,
					IALiteral.width * 1024 / jinganw,
					IALiteral.width * 702 / jinganw,
					IALiteral.width * 1024 / jinganw,
					IALiteral.width * 801 / jinganw,
					IALiteral.width * 891 / jinganw,
					IALiteral.width * 801 / jinganw },
			{/* B超121 */IALiteral.width * 891 / jinganw,
					IALiteral.width * 805 / jinganw,
					IALiteral.width * 1024 / jinganw,
					IALiteral.width * 805 / jinganw,
					IALiteral.width * 1024 / jinganw,
					IALiteral.width * 925 / jinganw,
					IALiteral.width * 891 / jinganw,
					IALiteral.width * 925 / jinganw },
			{/* 女内科128 */IALiteral.width * 632 / jinganw,
					IALiteral.width * 598 / jinganw,
					IALiteral.width * 788 / jinganw,
					IALiteral.width * 598 / jinganw,
					IALiteral.width * 788 / jinganw,
					IALiteral.width * 678 / jinganw,
					IALiteral.width * 632 / jinganw,
					IALiteral.width * 678 / jinganw },
			{/* 女外科127 */IALiteral.width * 632 / jinganw,
					IALiteral.width * 682 / jinganw,
					IALiteral.width * 788 / jinganw,
					IALiteral.width * 682 / jinganw,
					IALiteral.width * 788 / jinganw,
					IALiteral.width * 761 / jinganw,
					IALiteral.width * 632 / jinganw,
					IALiteral.width * 761 / jinganw },
			{/* 妇科126 */IALiteral.width * 632 / jinganw,
					IALiteral.width * 765 / jinganw,
					IALiteral.width * 788 / jinganw,
					IALiteral.width * 765 / jinganw,
					IALiteral.width * 788 / jinganw,
					IALiteral.width * 840 / jinganw,
					IALiteral.width * 632 / jinganw,
					IALiteral.width * 840 / jinganw },
			{/* 妇科125 */IALiteral.width * 632 / jinganw,
					IALiteral.width * 844 / jinganw,
					IALiteral.width * 788 / jinganw,
					IALiteral.width * 844 / jinganw,
					IALiteral.width * 788 / jinganw,
					IALiteral.width * 924 / jinganw,
					IALiteral.width * 632 / jinganw,
					IALiteral.width * 924 / jinganw },
			{/* 妇科000 */IALiteral.width * 1523 / jinganw,
					IALiteral.width * 256 / jinganw,
					IALiteral.width * 1731 / jinganw,
					IALiteral.width * 256 / jinganw,
					IALiteral.width * 1731 / jinganw,
					IALiteral.width * 356 / jinganw,
					IALiteral.width * 1523 / jinganw,
					IALiteral.width * 356 / jinganw } };
}
